puts "The Students of Villains Academy"
puts "--------------------------------"
puts "Freddy Krueger"
puts "The Terminator"
puts "Darth Vader"
puts "Nurse Radchet"
puts "Alex DeLarge"
puts "The Joker"
puts "Michael Corleone"
puts "Dr Hannibal Lecter"
puts "Norman Bates"
puts "Joffrey Baratheon"
puts "The Wicked Witch of the West"
print "Overall we have "
print 11
puts " great students."